### ISSUE TITLE
Senha solicita 8 caracteres mas precisa ser 9

### ISSUE THREAD

**Issue by Martbr** [ThomRamks/POO_2_Banco#17]
_Ao digitar os 8 caracteres, não esta sendo contabilizado, apenas valores maiores que 8._

**Onde:** Banco.java -> linha 94

**Solução:** Alterar argumento "<=8" para "<7"

Obs: aguardando subir versão mais atual para modificação.

**Comment by ThomRamks** [comment]
Resolvido para  não aceitar <8 (o pedido é para que a senha seja maior que 8).
